"""update field names

Revision ID: 2393113d9c3a
Revises: 85c46c842cae
Create Date: 2020-10-22 20:07:27.591225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2393113d9c3a'
down_revision = '85c46c842cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'nombre', new_column_name='first_name')
    op.alter_column('user', 'apellido', new_column_name='last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'first_name', new_column_name='nombre')
    op.alter_column('user', 'last_name', new_column_name='apellido')
    # ### end Alembic commands ###
