"""blocked field for users

Revision ID: 3be622233776
Revises: e792232e04c7
Create Date: 2020-12-23 18:55:08.534968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be622233776'
down_revision = 'e792232e04c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'blocked')
    # ### end Alembic commands ###
