"""add user register date column

Revision ID: e6111a3bc7fd
Revises: 4e665262dd51
Create Date: 2020-11-30 01:15:28.851345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6111a3bc7fd'
down_revision = '4e665262dd51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('register_date', sa.DateTime(), nullable=True))
    op.execute(f"""update "user" set register_date = 'now()'""")
    with op.batch_alter_table("user") as batch_op:
        batch_op.alter_column("register_date", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'register_date')
    # ### end Alembic commands ###
