"""add admin model

Revision ID: e792232e04c7
Revises: 8acb735fe1c7
Create Date: 2020-12-19 08:06:10.957130

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'e792232e04c7'
down_revision = '8acb735fe1c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'admin_user',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('first_name', sa.String(), nullable=False),
        sa.Column('last_name', sa.String(), nullable=False),
        sa.Column('_password', sa.String(), nullable=False),
        sa.Column(
            'email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False
        ),
        sa.Column('register_date', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_user')
    # ### end Alembic commands ###
