"""refactor user model

Revision ID: ee6d0160642a
Revises: 2393113d9c3a
Create Date: 2020-11-21 19:27:31.604630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee6d0160642a'
down_revision = '2393113d9c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column('_password', sa.String(), nullable=True))
    op.execute(
        """update "user" set _password = '$2b$12$oJ5CDLQ6LPluUJKC6fDGxORf4lXnlHtmjsRKq3XmoJZPRbzpBOWhO'"""
    )
    with op.batch_alter_table("user") as batch_op:
        batch_op.alter_column('_password', nullable=False)
        batch_op.alter_column(
            'email', existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column('first_name', existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column('last_name', existing_type=sa.VARCHAR(), nullable=False)
        batch_op.create_unique_constraint('unique_email', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user") as batch_op:
        batch_op.drop_constraint("unique_email", type_='unique')
        batch_op.alter_column('last_name', existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column('first_name', existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            'email', existing_type=sa.VARCHAR(length=255), nullable=True
        )
    op.drop_column('user', '_password')
    # ### end Alembic commands ###
